app:
  name: "Mikro"
  domain: "app.local"
ssl:
  enabled: true
  email: "support@example.com"
vendor:
  frontend:
    repo: "https://github.com/openware/cryptobase.git"
    branch: "customer/exq365-v2-connect-barong"
  tower: "https://github.com/openware/tower.git"
