- id:                   usd
  symbol:               '$'
  type:                 fiat
  precision:            8
  base_factor:          1
  enabled:              true
  deposit_fee:          0
  withdraw_fee:         0
  min_deposit_amount:   0
  name:                 'United States Dollar'
  withdraw_limit_24h:     100
  withdraw_limit_72h:     200

- id:                   eur
  symbol:               '€'
  type:                 fiat
  precision:            8
  base_factor:          1
  enabled:              true
  deposit_fee:          0
  withdraw_fee:         0
  min_deposit_amount:   0
  name:                 'Euro'
  withdraw_limit_24h:     100
  withdraw_limit_72h:     200

- id:                   eth
  symbol:               'Ξ'
  type:                 coin
  precision:            8
  base_factor:          1_000_000_000_000_000_000
  enabled:              true
  deposit_fee:          0
  withdraw_limit_24h:     100
  withdraw_limit_72h:     200
  withdraw_fee:         0
  min_deposit_amount:   0.00021
  name:                 'Ethereum'
  blockchain_key:       eth-rinkeby
  options:
    case_sensitive:                   false
    min_confirmations:                1
    supports_cash_addr_format:        false
    supports_hd_protocol:             false
    allow_multiple_deposit_addresses: false
    api_client: ETH
    json_rpc_endpoint:        http://geth:8545
    wallet_url_template:      https://rinkeby.etherscan.io/address/#{address}
    transaction_url_template: https://rinkeby.etherscan.io/tx/#{txid}

- id:                   trst
  symbol:               'Ξ'
  type:                 coin
  precision:            8
  base_factor:          1_000_000
  enabled:              true
  min_deposit_amount:   1.7
  name:                 'WeTrust'
  withdraw_limit_24h:     100
  withdraw_limit_72h:     200
  blockchain_key:       eth-rinkeby
  options:
    case_sensitive:                   false
    min_confirmations:                1
    supports_cash_addr_format:        false
    supports_hd_protocol:             false
    allow_multiple_deposit_addresses: false
    api_client: ERC20
    json_rpc_endpoint:        http://geth:8545
    erc20_contract_address:   '0x87099adD3bCC0821B5b151307c147215F839a110'
    wallet_url_template:      https://rinkeby.etherscan.io/address/#{address}
    transaction_url_template: https://rinkeby.etherscan.io/tx/#{txid}
